### ISSUE TITLE
Huggingface version is not working

### ISSUE THREAD

**Issue by hadifar** [VinAIResearch/BERTweet#14]
# error
When I execute the huggingface version It throws the following error:

`OSError: Model name 'vinai/bertweet-base' was not found in tokenizers model name list (roberta-base, roberta-large, roberta-large-mnli, distilroberta-base, roberta-base-openai-detector, roberta-large-openai-detector). We assumed 'vinai/bertweet-base' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.

`

# reproduce

https://colab.research.google.com/drive/1bwWQAX9Ql0d1fTVSQd1KpP2AQledgyKZ?usp=sharing

**Comment by datquocnguyen** [comment]
BERTweet will soon be merged into the master branch of huggingface's `transformers`. For now, you would have to install `transformers` from our development branch. Did you try the following commands?

 -  Python version >= 3.6
 - [PyTorch](http://pytorch.org/) version >= 1.4.0
 -  Install `transformers` from our development branch:
    - `git clone https://github.com/datquocnguyen/transformers.git`
    - `cd transformers`
    - `pip3 install .`
 - Install `emoji`: `pip3 install emoji`

**Comment by hadifar** [comment]
Thanks for your reply! Installing from
