### ISSUE TITLE
Could you share the pre-processed tweet data?

### ISSUE THREAD

**Issue by RensDimmendaal** [VinAIResearch/BERTweet#23]
Hi all,

Thanks for the great work! I used it to make this little emoji recommender: 

[http://rensdimmendaal.com/emoji/](http://rensdimmendaal.com/emoji/)

I'd love to expand the number of different emoji I can recommend. However, I cannot at the moment, because some emoji are split into multiple tokens. Would you be willing to share the preprocessed data of bertweet-base so I can add these as single tokens to the vocabulary and tune the model?

**Comment by abhinavkashyap** [comment]
Is there any way that you could share the preprocessed dataset? I require it for research purposes as well

**Comment by CharleoY** [comment]
> Hi all,
> 
> Thanks for the great work! I used it to make this little emoji recommender:
> 
> http://rensdimmendaal.com/emoji/
> 
> I'd love to expand the number of different emoji I can recommend. However, I cannot at the moment, because some emoji are split into multiple tokens. Would you be willing to share the preprocessed data of bertweet-base so I can add these as single tokens to the vocabulary and tune the model?

Maybe it is due to the queue of preprocess? you may put some regex pattern like ' : ' or '_' after demojized?

**Comment by datquocnguyen** [comment]
> Is there any way that you could share the preprocessed dataset? I require it for research purposes as well

Unfortunately, I could not.
