### ISSUE TITLE
Re-training the language model

### ISSUE THREAD

**Issue by damlitos** [VinAIResearch/BERTweet#27]
Hi all,

Thank you for the great work! This will solve the problem of adapting BERT (trained on Wikipedia and the book corpus) to the tweet domain.  Of course, the problems such as adapting it to own domain of tweet data is still there. For this purpose, it would be useful to re-train the BERTweet language model first to teach BERTweet to speak the language of a specific domain. I have been investigating some tutorials and the trainer module of transformers. Do you have any guidance, script or a tutorial that can be shared? 

Many thanks

**Comment by datquocnguyen** [comment]
Hi, there are many script/tutorial examples for a wide range of NLP tasks available at: https://github.com/huggingface/transformers/tree/master/examples

**Comment by datquocnguyen** [comment]
Sorry, my bad. I follow the following tutorial to train BERTweet: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md

**Comment by datquocnguyen** [comment]
You can also use script examples from https://github.com/huggingface/transformers/tree/master/examples/language-modeling to fine-tuning BERTweet on a specific-domain corpus.
