### ISSUE TITLE
Can't load Tokenizer

### ISSUE THREAD

**Issue by mahboriola** [VinAIResearch/BERTweet#28]
When trying to load the Tokenizer using the following code:
```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base")
```

I got these error messages:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-4-5cebf451220a> in <module>()
>       1 from transformers import AutoTokenizer
> ----> 2 tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base")
> 
> /usr/local/lib/python3.6/dist-packages/transformers/models/auto/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
>     368             if use_fast and not config.tokenizer_class.endswith("Fast"):
>     369                 tokenizer_class_candidate = f"{config.tokenizer_class}Fast"
> --> 370                 tokenizer_class = tokenizer_class_from_name(tokenizer_class_candidate)
>     371             if tokenizer_class is None:
>     372                 tokenizer_class_candidate = config.tokenizer_class
> 
> /usr/local/lib/python3.6/dist-packages/transformers/models/auto/tokenization_auto.py in tokenizer_class_from_name(class_name)
>     271     )
>     272     for c in all_tokenizer_classes:
> --> 273         if c.__name__ == class_name:
>     274             return c
>     275 
> 
> AttributeError: 'NoneType' object has no attribute '__name__'

Python 3.6.9
Transformers 4.3.2

**Comment by datquocnguyen** [comment]
From README.md file:

    # For transformers v4.x+: 
    tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base", use_fast=False)
