### ISSUE TITLE
Some emojis not tokenized properly

### ISSUE THREAD

**Issue by AkemiHomura-maow** [VinAIResearch/BERTweet#29]
Hi dev team
I appreciate you guys for making this model to facilitate nlp research in tweets! I have been trying to use the BERTweet to do my project on Twitter, however I think I've just found something weird with the tokenization step. 
The 'Example usage' tab in README gives a sample tweet: "SC has first two presumptive cases of coronavirus , DHEC confirms HTTPURL via @USER :cry:"
I tried to tokenize this tweet with AutoTokenizer.from_pretrained("vinai/bertweet-base", use_fast=False), then use print(tokenizer.convert_ids_to_tokens(tokenizer.encode(line))), I get:

`['<s>', 'SC', 'has', 'first', 'two', 'presum@@', 'ptive', 'cases', 'of', 'coronavirus', ',', 'D@@', 'HE@@', 'C', 'confirms', 'HTTPURL', 'via', '@USER', '<unk>', ':', '</s>']`

Or with AutoTokenizer.from_pretrained("vinai/bertweet-base", use_fast=False, normalization=True), I get:
`['<s>', 'SC', 'has', 'first', 'two', 'presum@@', 'ptive', 'cases', 'of', 'coronavirus', ',', 'D@@', 'HE@@', 'C', 'confirms', 'HTTPURL', 'via', '@USER', ':', 'cry', ':', '</s>']`

Either way, the tokenization is not correct for the emoji string ":cry:"

I have checked the source code implemented in Transformer, I think what went wrong is that for emoji.demojizer(), you need to set the option use_aliases=True to cover all emojis, otherwise some just won't get included. 

I have also checked `tokenizer.get_vocab()[':cry:']`, and it returns a KeyError

**Comment by datquocnguyen** [comment]
What happens if using `BertweetTokenizer` instead of `AutoTokenizer`?

**Comment by AkemiHomura-maow** [comment]
> What happens if using `BertweetTokenizer` instead of `AutoTokenizer`?

Hi thanks for the quick response, it's still the same.
![image](https://user-images.githubusercontent.com/34213712/115120577-c5812d00-9fe0-11eb-97b5-e6aa288e96eb.png)

**Comment by datquocnguyen** [comment]
It's strange, I ran a similar example and did not get any problem. In my example, 😢 is converted into `:crying_face:` instead of `:cry:` 

Which is the `transformers` version you using? Have you installed `pip3 install emoji`? 

<img width="960" alt="Screen Shot 2021-04-18 at 4 00 29 pm" src="https://user-images.githubusercontent.com/2412555/115139993-3ebf6500-a05f-11eb-8f88-7982247a6043.png">

**Comment by AkemiHomura-maow** [comment]
Hi, I wasn't trying with real tweets. Yes the real ones should work.
![image](https://user-images.githubusercontent.com/34213712/115153513-ef9e2200-a0a8-11eb-9108-b2e957b408b7.png)
The emoji in the sample somehow becomes :cry: instead of being retained as 😢, which translates to :crying_face:.

**Comment by datquocnguyen** [comment]
Installation: pip3 install nltk emoji==0.6.0
The emoji version must be either 0.5.4 or 0.6.0. Newer emoji versions have been updated to newer versions of the Emoji Charts, thus not consistent with the one used for pre-processing our pre-training Tweet corpus.
