### ISSUE TITLE
How do I perform sentiment analysis using it?

### ISSUE THREAD

**Issue by gaganmanku96** [VinAIResearch/BERTweet#3]

**Comment by datquocnguyen** [comment]
We will release our scripts to reproduce our results soon (after emnlp&coling deadlines). 
It should not be difficult to make minor changes to https://github.com/huggingface/transformers/blob/master/examples/text-classification/run_glue.py with the sst-2 task_name See: https://github.com/huggingface/transformers/tree/master/examples/text-classification

**Comment by yxchng** [comment]
@datquocnguyen any updates on this?

**Comment by jsherrah** [comment]
@datquocnguyen thanks for your code.  When will you release the scripts for downstream tasks?
