### ISSUE TITLE
Use model output for sentiment classifcation

### ISSUE THREAD

**Issue by wtsong** [VinAIResearch/BERTweet#32]
Thanks a lot for the work on BERTweet.  In the paper you describe using the model for 3-class sentiment analysis.  Can you please provide an example how it is done?

The readme example:

    bertweet = AutoModel.from_pretrained("vinai/bertweet-base")
    tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base", use_fast=False)
    line = "SC has first two presumptive cases of coronavirus , DHEC confirms HTTPURL via @USER :crying_face:"
    input_ids = torch.tensor([tokenizer.encode(line)])
    with torch.no_grad():
        features = bertweet(input_ids)

produces the results

    # Inspect results
    print(f'Pooler outputs shape: {features["pooler_output"].shape}')
    print(f'Last hidden states shape: {features["last_hidden_state"].shape}')

> Pooler outputs shape: torch.Size([1, 768])
> Hidden states shape: torch.Size([1, 20, 768])

How do you then use the model outputs to classify the sentiment of the tweet?

**Comment by datquocnguyen** [comment]
`How do you then use the model outputs to classify the sentiment of the tweet?`
We fine-tune BERTweet for a text classification task: https://github.com/huggingface/transformers/tree/master/examples/pytorch/text-classification

**Comment by wtsong** [comment]
Thanks, Dat Quoc. So, would it be something like the command below? i.e. changing `--model_name_or_path` to `vinai/bertweet_base` and tweaking `--dataset_name` to point to my input data?

    python run_glue.py \
      --model_name_or_path vinai/bertweet_base \
      --dataset_name imdb  \
      --do_train \
      --do_predict \
      --max_seq_length 128 \
      --per_device_train_batch_size 32 \
      --learning_rate 2e-5 \
      --num_train_epochs 3 \
      --output_dir /tmp/imdb/
