### ISSUE TITLE
AutoTokenizer gives error

### ISSUE THREAD

**Issue by GeetDsa** [VinAIResearch/BERTweet#33]
The sample script provided [here](https://huggingface.co/vinai/bertweet-base) gives error. The script is given below:

```
import torch
from transformers import AutoModel, AutoTokenizer

bertweet = AutoModel.from_pretrained("vinai/bertweet-base")
tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base")

# INPUT TWEET IS ALREADY NORMALIZED!
line = "SC has first two presumptive cases of coronavirus , DHEC confirms HTTPURL via @USER :cry:"

input_ids = torch.tensor([tokenizer.encode(line)])

with torch.no_grad():
    features = bertweet(input_ids)

```

Error:

> Traceback (most recent call last):
>   File "temp.py", line 5, in <module>
>     tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base")
>   File "<conda_env>//lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 372, in from_pretrained
>     tokenizer_class = tokenizer_class_from_name(tokenizer_class_candidate)
>   File "<conda_env>/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 275, in tokenizer_class_from_name
>     if c.__name__ == class_name:
> AttributeError: 'NoneType' object has no attribute '__name__'

The error is resolved by using:

```
tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base", use_fast=False)
```

**Comment by datquocnguyen** [comment]
Right. That sample script is out of date, used for transformers v3.x.
The latest examples are available at: https://github.com/VinAIResearch/BERTweet
