### ISSUE TITLE
Applying Bertweet to a huge pandas dataframe

### ISSUE THREAD

**Issue by lightmagic1** [VinAIResearch/BERTweet#35]
Hello everyone :) 

I'm a psychologist researcher studying user behaviour on social media.

As part of my research, i get a huge amount of tweets on a specific hashtag (~25.000.000 tweets). 

I would like to do sentiment analysis on this dataset, i previously used the default HugginFace for SA, but the results weren't that great:

```python
classifier = pipeline("sentiment-analysis")

tweets_df['sentiment'] = tweets_df['text'].apply(lambda row : (classifier(row))[0]['label'])
```
I run the example code on the main gh page:

![image](https://user-images.githubusercontent.com/47085387/156241855-36f5d1da-ce06-43dc-b97d-e22e747177ad.png)

I'm here asking for some guidance, of how can i apply it now **in a performatic way** and get a new column called 'sentiment' with sentiment analysis of each row?

**Comment by datquocnguyen** [comment]
You should use BERTweet-based models which were fine-tuned for the downstream sentiment analysis task such as https://huggingface.co/finiteautomata/bertweet-base-sentiment-analysis or https://huggingface.co/cardiffnlp/bertweet-base-sentiment.
