### ISSUE TITLE
Preprocessing of tweets

### ISSUE THREAD

**Issue by pepi99** [VinAIResearch/BERTweet#38]
Hello,
I saw your preprocessing steps (where you convert links and mentions to :USER and HTTPURL , but I am wondering, when you trained BERTweet, I imagine there can be strange tokens/symbols and so on, so where you mask 15% of the tokens for each sentence, why does the model not get confused when trying to predict for example ":@" or ":D" or some strange symbols? 

Regards

**Comment by datquocnguyen** [comment]
I might not quite understand your question.
Strange tokens/symbols should be referred to as rare (subword) tokens, thus they are converted to the "unknown" one during training.
