### ISSUE TITLE
About the tokenizer for Bertweet-Large

### ISSUE THREAD

**Issue by qhd1996** [VinAIResearch/BERTweet#42]
I download the model wieght and config file form https://huggingface.co/vinai/bertweet-large and find that the vocab and tokenizer are different from those in Bertweet-Base(https://huggingface.co/vinai/bertweet-base). Moreover, I cannot find the ':crying_face:' token in large version's vocab.json. The tokenizer seems more like a RoBERTaTokenizer inestad of BertweetTokenizer. May the researchers introduce the changes?

**Comment by datquocnguyen** [comment]
Yes. It was difficult to develop a fast BertweetTokenizer variant a year ago. So, I used RobertaTokenizer when pre-training [bertweet-large](https://huggingface.co/vinai/bertweet-large) for its wider usage.
