### ISSUE TITLE
next sentence prediction

### ISSUE THREAD

**Issue by naarkhoo** [VinAIResearch/BERTweet#43]
Thanks for developing BERTweet
here is a conceptual question when it comes to utilizing tweets for training BERT model and I am curious how you have handled that.

Bert Language model has a "next sentence prediction" model, where through building the LM model try to optimize predicting the next sentence. 

since tweets are short and often contain one sentence. I am curious how you have handled that and how have you bypassed NSP part ?

Thank you again.

**Comment by datquocnguyen** [comment]
Hi, our BERTweet is based on RoBERTa which does not include the NSP task.
