### ISSUE TITLE
vinai/bertweet-large returns LABEL_0 all the time

### ISSUE THREAD

**Issue by damlitos** [VinAIResearch/BERTweet#44]
Hi all, I have something fish going on with bertweet-large model. The code and the output is below. I also test a dataset of 5000 tweets and it returns label_0 for all of them. Do you have any ideas what might be the issue?

Thanks

Best

# CODE
classifier = pipeline('sentiment-analysis',  model="vinai/bertweet-large") # , return_all_scores = True)

print(classifier('I hate you'))

print(classifier('I love you'))

print(classifier('I you'))

# OUTPUT 
[{'label': 'LABEL_0', 'score': 0.6324337720870972}]
[{'label': 'LABEL_0', 'score': 0.6408738493919373}]
[{'label': 'LABEL_0', 'score': 0.6261811256408691}]

**Comment by datquocnguyen** [comment]
`vinai/bertweet-large` has not been fine-tuned for sentiment analysis yet. You should fine-tune it on a sentiment analysis dataset, then you can use the fine-tuned model for sentiment analysis.
