### ISSUE TITLE
Tokenizer vinai/bertweet-covid19-base-uncased

### ISSUE THREAD

**Issue by volhakatebi** [VinAIResearch/BERTweet#45]
Does vinai/bertweet-covid19-base-uncased use the same tokenizer as bertweet-base? I've been trying to run a code on my annotated data and keeps giving me an error "index is out of range in self" during train stage if I download model and tokenizer from bertweet-covid19-base-uncased. The only way it worked for me was using the model from bertweet-covid19-base-uncased  and tokenizer from bertweet-base.

**Comment by datquocnguyen** [comment]
It's strange. Both use the same tokenizer.

**Comment by volhakatebi** [comment]
Thank you for your quick response! The code with my dataset work for bertweet-base model & bertweet-base tokenizer but somehow it keeps giving me this index error when using tokenizer from bertweet-covid19-base-uncased. I guess I will use bert-base tokenizer with bertweet-covid19-base-uncased model after confirming that it is the same tokenizer.

**Comment by datquocnguyen** [comment]
Yeah, you can just simply `diff`tokenizers files (vocab.txt, bpe.codes, tokenizer.json). They're the same.
