### ISSUE TITLE
IndexError: index out of range in self

### ISSUE THREAD

**Issue by kkkkk001** [VinAIResearch/BERTweet#46]
Hi, I encountered an error: "IndexError: index out of range in self." Below is my code. Can you help identify where the problem is? Is it related to the length of the sequence? I can provide the specific text if you need it.

```
pretrain_model = 'vinai/bertweet-base'
tokenizer = AutoTokenizer.from_pretrained(pretrain_model)
model = AutoModelForMaskedLM.from_pretrained(pretrain_model)

inputs = tokenizer(text, return_tensors="pt", padding='max_length', truncation=True, max_length=512)
last_hidden_states = model(**inputs, output_hidden_states=True).hidden_states[-1]
```

**Comment by kishan2k2** [comment]
is print(len(tokenizer(text)["input_ids"])) less than 512?

**Comment by datquocnguyen** [comment]
@kkkkk001 You're using the base model which has a max sequence length of 128.
