### ISSUE TITLE
Sentimental analysis of tweets.

### ISSUE THREAD

**Issue by kishan2k2** [VinAIResearch/BERTweet#47]
I want to do a sentimental analysis of the tweets and I want to use this model for that purpose.

Can someone provide me a high-level overview of what/How I should be doing to accomplish my task?

**Comment by datquocnguyen** [comment]
Here is an example: https://huggingface.co/finiteautomata/bertweet-base-sentiment-analysis 
You can fine-tune bertweet for sentiment classification as in: https://github.com/huggingface/transformers/tree/v4.34.1/examples/pytorch/text-classification
