### ISSUE TITLE
Host the model on Huggingface?

### ISSUE THREAD

**Issue by zijwang** [VinAIResearch/BERTweet#5]
It would be nice to have the model also hosted on huggingface (https://huggingface.co/models), so people could use it from the huggingface API without manually downloading the model dump.

**Comment by datquocnguyen** [comment]
We'd do that as soon as we can (all authors are now busy with emnlp & coling conference submissions).

**Comment by datquocnguyen** [comment]
I am waiting for tranformers' developers to merge my pull request. In the meantime, you can use the BERTweet from this folk: https://github.com/datquocnguyen/transformers 

    git clone https://github.com/datquocnguyen/transformers
    cd transformers
    pip install .

Example is available at: https://github.com/datquocnguyen/transformers/tree/master/model_cards/vinai/bertweet-base 
   
    bertweet = BertweetModel.from_pretrained("vinai/bertweet-base")
    tokenizer = BertweetTokenizer.from_pretrained("vinai/bertweet-base")
