### ISSUE TITLE
error while running the sample code

### ISSUE THREAD

**Issue by vineeth567** [VinAIResearch/BERTweet#6]
Hi,
I am using google colab and trying to run the sample usage code you have given, 
`from fairseq.data.encoders.fastbpe import fastBPE  
from fairseq import options  
parser = options.get_preprocessing_parser()  
parser.add_argument('--bpe-codes', type=str, help='path to fastBPE BPE',default="BERTweet_base_fairseq/bpe.codes")  
args = parser.parse_args()  `

I'm facing an issue while passing args.
The error is in attached img. How do i have this error?
![Screenshot from 2020-06-02 10-48-24](https://user-images.githubusercontent.com/49122145/83482785-c4c1d400-a4be-11ea-80fe-896b84a75f0b.png)

**Comment by mcdavid109** [comment]
I just checked this issue on my machine and have no problems
