### ISSUE TITLE
Way to mask multiple words in a sentence?

### ISSUE THREAD

**Issue by vineeth567** [VinAIResearch/BERTweet#9]
Hi,
Is there a way to mask multiple words in a sentence?

Thanks in advance.

**Comment by datquocnguyen** [comment]
Do you mean in training or inference phase?

**Comment by vineeth567** [comment]
Inference phase.

**Comment by datquocnguyen** [comment]
You might use a beam search to sequently predict each <mask> (from left to right) based on its unmasked context.
"How <mask> are" => "How <1st_masked_candidate> are <mask>", "How <2nd_masked_candidate> are <mask>", "How <3rd_masked_candidate> are <mask>".
